### ISSUE TITLE
man page errata?

### ISSUE THREAD

**Issue by Casteele72** [flightaware/tclcurl-fa#18]
The man page says option "-post301" used to be called option "-post301" ... That is confusing. Does that mean the option name actually changed, but did not get updated in the docs? Or is the reference to the previous option name incorrect?

**Comment by bovine** [comment]
I agree that seems confusing. It seems to have existed since before 2014, so we don't have revision history in this repo to see the origins for that comment. Additionally, I don't see any indication in the code that there is an alias for that option

https://github.com/flightaware/tclcurl-fa/blob/master/doc/tclcurl.n#L782

In any case, that is an old remark about an even older option (that may not exist anymore?) so I'll just remove it.
